module.exports = {
  actionTypes: {
    FETCH_REQUEST: 'FETCH_REQUEST',
    FETCH_FAILED: 'FETCH_FAILED',
    FETCH_SUCCEED: 'FETCH_SUCCEED',
    FETCH_POSTS_SUCCEED: 'FETCH_POSTS_SUCCEED',
    FETCH_POSTS_FAILED: 'FETCH_POSTS_FAILED',
    FETCH_POSTS_REQUEST: 'FETCH_POSTS_REQUEST'
  }
};
